### ISSUE TITLE
unable to pull submodules

### ISSUE THREAD

**Issue by Holo-Viktor** [keijiro/Voxelman#13]
I don't have permissions to update the submodules...

**Comment by keijiro** [comment]
This repository uses ssh for submodules. [Add SSH key to your GitHub account](https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent), or modify `.gitmodules` to use https instead of ssh.

By the way, this project is not compatible with the recent versions of Unity. I don't recommend using this project as an ECS example.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
